name: Go
on:
  workflow_call:
    inputs:
      unit:
        description: Command to run tests
        required: false
        type: string
        default: 'go test ./...'
    secrets:
      github-token:
        description: GitHub token
        required: true

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ["self-hosted", "stage", "default"]
    container:
      image: golang:1.18-bullseye
    steps:
      - uses: actions/checkout@v2
      -
        name: Run tests
        run: |
          mkdir -p /run/secrets && echo '${{ secrets.github-token }}' > /run/secrets/github_token
          . .github/scripts/git-askpass-helper
          ${{ inputs.unit }}

  static-check:
    name: Static check
    runs-on: ["self-hosted", "stage", "default"]
    container:
      image: golang:1.18-bullseye
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    -
      name: Export GIT_ASKPASS
      run: |
        mkdir -p /run/secrets && echo '${{ secrets.github-token }}' > /run/secrets/github_token
        . .github/scripts/git-askpass-helper
        echo "GIT_ASKPASS=${GIT_ASKPASS}" >> ${GITHUB_ENV}
    -
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"
        install-go: false

  nancy:
    name: Nancy
    runs-on: ["self-hosted", "stage", "default"]
    container:
      image: golang:1.18-bullseye

    steps:
    - uses: actions/checkout@v2
    -
      name: Export GIT_ASKPASS
      run: |
        mkdir -p /run/secrets && echo '${{ secrets.github-token }}' > /run/secrets/github_token
        . .github/scripts/git-askpass-helper
        echo "GIT_ASKPASS=${GIT_ASKPASS}" >> ${GITHUB_ENV}
    -
      name: WriteGoList
      run: go list -json -m all > go.list
    -
      name: Nancy
      uses: sonatype-nexus-community/nancy-github-action@main
