name: Helmfile Deploy
on:
  workflow_call:
    inputs:
      repository:
        description: Docker repository name (ex. organization)
        required: false
        type: string
      release:
        description: Helmfile release name to deploy (equal github repository name by default)
        required: false
        type: string
      tag:
        description: Helmfile release tag to deploy
        required: true
        type: string
      labels:
        description: Helmfile additional label selectors
        required: false
        type: string
      concurrency:
        description: Process the given number of simultaneous release at a time (scoped by a single helmfile)
        required: false
        default: 20
        type: number
      runs-on:
        description: Specifies runs-on for the workflow jobs
        default: ubuntu-latest
        required: false
        type: string
      helm-infra-ref:
        description: Specifies helm-infra ref
        default: master
        required: false
        type: string
    secrets:
      helm-infra-token:
        description: GitHub token to clone helm-infra
        required: true

jobs:
  pre:
    name: Prepare
    runs-on: ubuntu-latest

    outputs:
      release: ${{ steps.set.outputs.release }}
      self-hosted: ${{ steps.set.outputs.push }}
      runs-on: ${{ steps.set.outputs.runs-on }}
      jobOutcomes: ${{ steps.set.outputs.jobOutcomes }}
      environment: ${{ steps.envmap.outputs.environment }}

    steps:
      -
        name: Map runtime environment data
        id: envmap
        uses: kanga333/variable-mapper@master
        with:
          key: ${{ github.ref }}
          export_to: output
          mode: overwrite
          map: |
            {
              "^refs/heads/development$": { "environment": "stage" },
              "^refs/tags/v[0-9]+.[0-9]+.[0-9]+(-.*)?$": { "environment": "prod" }
            }
      -
        uses: actions/github-script@v5
        id: set
        with:
          script: |
            //js
            const releaseName = '${{ inputs.release || github.event.repository.name }}'.toLowerCase()
            core.setOutput('release', releaseName)

            // safe-escape escape hosted runner
            let runsOn = '${{ inputs.runs-on }}'
            let selfHosted = true
            if ('${{ inputs.runs-on }}'.trim().match(/^(\w|[-.])+$/)) {
              runsOn = '"${{ inputs.runs-on }}"'
              selfHosted = false
            }
            core.setOutput('runs-on', runsOn)
            core.setOutput('self-hosted', selfHosted)

            // job outcomes choice
            core.setOutput('jobOutcomes', '{"cancelled":"failure","failure":"failure","success":"success"}')
            //!js

  deploy:
    name: Apply
    needs: [pre]
    runs-on: ${{ fromJSON(needs.pre.outputs.runs-on) }}
    container:
      image: dysnix/kubectl:v1.20-gcloud

    env:
      # github actions secret (w/ kubeconfig)
      secret: zigiai-${{ needs.pre.outputs.environment }}-infra-github-actions
      environment: ${{ needs.pre.outputs.environment }}
      selector: name=${{ needs.pre.outputs.release }},${{ inputs.labels }}
      IMAGE_TAG: ${{ inputs.tag }}

    steps:
      -
        uses: actions/checkout@v2
        with:
          repository: zigiai/helm-infra
          ref: ${{ inputs.helm-infra-ref }}
          token: ${{ secrets.helm-infra-token }}
      -
        name: Map Environment to Project ID
        id: envToProject
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -o=j '.envToProject' .github/config.yaml
      -
        name: Info
        run: |
          echo "==> Environment: $environment"
          echo "==> Selectors: ${selector%,}"
          echo "==> Image Tag: $IMAGE_TAG"
          echo
          pwd
          ls -la
      -
        name: Helmfile Apply
        # if: env.environment != ''
        env:
          project_id: ${{ fromJson(steps.envToProject.outputs.result)[env.environment] }}

        run: |
          ## setup ~/.kube/config
          ## Helmfile environment corresponds to the cluster in the secret! (ex clusters.stage etc)
          echo ./scripts/fetch-kubeconfig $secret $environment $project_id

          echo UPDATE_REPOS=y helmfile -e $environment repos
          echo helmfile -e $environment -l ${selector%,} apply --concurrency ${{ inputs.concurrency }}
