name: Sonarqube

on:
  workflow_call:
    inputs:
      default-branch-only:
        description: Force checks on the default branch only
        required: false
        default: true
        type: boolean
    secrets:
      token:
        description: GitHub token to clone helm-infra
        required: true

env:
  SONARQUBE_HOST: https://sonarqube.stage.zigi.app

jobs:
  sonarqube:
    name: Scan
    runs-on: [self-hosted, default, stage]
    container:
      image: golang:1.18-bullseye

    steps:
      - uses: actions/github-script@v5
        id: cfg
        with:
          script: |
            let run = false
            let defaultBranch = ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}

            if (${{ inputs.default-branch-only }} == true && defaultBranch) {
              run = true
            }

            core.setOutput('run', run)
      -
        uses: actions/checkout@v2
        if: steps.cfg.outputs.run == 'true'
          
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.1.1
        if: steps.cfg.outputs.run == 'true'
        with:
          host: ${{ env.SONARQUBE_HOST }}
          login: ${{ secrets.token }}
